### ISSUE TITLE
Wordpress - Hidden Field That shows "current page title"

### ISSUE THREAD

**Issue by zakkates** [BFTrick/jotform-integration#3]
For an eCommerce site, it would be great to have 1 form show on all of the different product pages, and then when the form is received, the form can tell us from what url, or more specifically, what <?php the_title(); ?> of the page is

**Comment by BFTrick** [comment]
Hi @zakkates ! Thanks for submitting this issue.

Sadly, JotForms are in an `iframe` so basically they are a totally separate entity and can't interact with the outside page. So your request is impossible. This is just how JotForm works. :(

Have you looked into something like [Ninja Forms](http://wordpress.org/plugins/ninja-forms/). It's free and _can_ interact with elements on the page.

**Comment by zakkates** [comment]
not true :-p

See here: http://www.jotform.com/help/95-How-to-Know-The-Exact-URL-Of-a-Page-Where-a-Form-Submission-Is-Made

I figured out. Works great! 

Jotform works on Script, so, of course it can grab the current href like so: window.location.href 

This was my original embed script that jotform gives me: 

<script type=\"text/javascript\" src=\"http://form.jotform.co/jsform/31977130495864?product=\"></script>

This one will show me the URL of where the contact form was filled out: 

<script type="text/javascript">
document.write(" <script src=\"http://form.jotform.co/jsform/31977130495864?product= " + window.location.href + " \"></ " + " script> ");
</script>

Using wordpress I also figured out another way to print the_title() .... but the href works for now, so I'll see what the client says. Anything is possible :-p

**Comment by BFTrick** [comment]
Awesome! I love it when people prove me wrong! :)

**Comment by zakkates** [comment]
:-)

Best Regards,

Sent from my iPhone.

Zakery Kates
Simple Edge, Inc.
www.Simple-Edge.com
(o) 312.834.3343
(c) 630.863.1775
