### ISSUE TITLE
How is this licensed?

### ISSUE THREAD

**Issue by ghost** [BFTrick/jotform-integration#5]
I noticed some of this code is being used in [derivative works](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy). The README says it's licensed under GPL but the repo doesn't contain a copy of the GPL. Is there any reason the GPL copying file isn't included – or was that just an oversight?

**Comment by BFTrick** [comment]
Just an oversight. Feel free to send a PR with the GPL license. :)

**Comment by ghost** [comment]
It's a pretty personal choice. I'll leave that one up to you. Thanks.
